# Generated by Django 4.0.4 on 2022-05-05 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildings', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='rooms',
            name='availability',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 5)),
        ),
    ]
